
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import mathlearning.LearnMath;
//import mathlearning.MathLearning;


/**
 *
 * @author AN  IK
 */
public class MathLearningGUI extends javax.swing.JFrame {
    
    public static int countLowestScore=0,countHighestScore=0,countGame=0;
    public  int score=0,totalGameScore=0;
    public int userAnswer;
    static String Summary="",inputnum="",profile="";
    public static     String  number="";
    public  int n=0,n1,n2,n7,n8,n6,n5,s=0,t=0;
    double u=0,gameParsentage=0;
    double n3,n4;
    String operation;

    /**
     * Creates new form MathLearningGUI
     */
    
    public int countHighestScore(int score){
        if(countHighestScore<score){
             countHighestScore=score;
        }
        return countHighestScore;
    }
    public int countLowestScore(int score){
        if(countHighestScore>score){
            countLowestScore=score;
               
        }
        return countLowestScore;
    }
    public MathLearningGUI() {
        initComponents();
        init();
      
    }
    public void init(){
        setLocationRelativeTo(null);
    }
    public int sumCheck(int n1,int n2){
        this.n1=n1;
        this.n2=n2;
        return n1+n2;
    }
    public void checkSum(){
        n1=(int) (Math.random()*20);
        n2=(int) (Math.random()*20);
        jTextArea1.setText(n1+" + "+n2+"= ?"+"\n");
        // s=Integer.parseInt(n1+" + "+n2+"= ?"+"\n");
        operation="+";
        sumCheck(n1, n2);
    }
    public void checkSub(){
        n5=(int) (Math.random()*20);
        n6=(int) (Math.random()*20);
        jTextArea1.setText(n5+" - "+n6+"= ?"+"\n");
        operation="-";
    }
    public void checkMul(){
        n7=(int) (Math.random()*20);
        n8=(int) (Math.random()*20);
        jTextArea1.setText(n7+" X "+n8+"= ?"+"\n");
        operation="X";
    }
    public void checkDiv(){
            n3=(int) (Math.random()*20);
            n4=(int) (Math.random()*20);
            if(n3==0||n3==1)n3+=2;
            if(n4==0||n4==1)n4+=2;
            if(n4>n3)
            {
                double temp =n4;
                n4=n3;
                temp =n3;
            }
            jTextArea1.setText((int)n3+" / "+(int)n4+"= ?"+"\n");
            operation="/";
    }
    public void newGame(){
        int n = (int)(Math.random()*4);
        //n=0;
            switch(n)
            {
                case 0:
                    
                    checkSum();
                    
                    break;
                case 1:
                    
                    checkSub();
                    
                    break;
                case 2:
                    
                    checkMul();
                    
                    break;
                case 3:
                    
                    checkDiv();
                    
                    break;
            }
    }
    public double gameParsentage(){
    return gameParsentage=(countGame/totalGameScore);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonHistory = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonProfile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonNewGame = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonScore = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true), new javax.swing.border.MatteBorder(null))));

        jButtonHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonHistory.setText("History");
        jButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoryActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_stock_exit_29650.png"))); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonProfile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_users-10_984119 (1).png"))); // NOI18N
        jButtonProfile.setText("Profile");
        jButtonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfileActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 0));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Developed By -Md Rakib Hasan Anik");

        jButtonNewGame.setBackground(new java.awt.Color(204, 102, 255));
        jButtonNewGame.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNewGame.setText("New Game");
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButtonPoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPoint.setText(".");
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setText("←");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonScore.setText("Score");
        jButtonScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScoreActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 51, 102));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_help_forum-lb_86236.png"))); // NOI18N
        jButton11.setText("Help");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jLabel5.setText("Back to LogIn!");

        jButtonLogIn.setText("Log In");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonLogIn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNewGame))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonScore, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        // TODO add your handling code here:
//        checkSum();
//        checkSub();
//        checkMul();
//        checkDiv();
       //newGame();
       countGame++;
       Summary="";
       number="";
       //score=0;
       int n = (int)(Math.random()*4);
        //n=0;
            switch(n)
            {
                case 0:
                    checkSum();
                    
                    
                    break;
                case 1:
                    checkSub();
                    
                    break;
                case 2:
                    checkMul();
                    
                    break;
                case 3:
                    checkDiv();
                    
                    break;
            }
            
 
        
    }//GEN-LAST:event_jButtonNewGameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         inputnum=jTextArea1.getText()+jButton1.getText();
         number=number+jButton1.getText();
        jTextArea1.setText(inputnum);
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         inputnum=jTextArea1.getText()+jButton3.getText();
         number=number+jButton3.getText();
        jTextArea1.setText(inputnum);
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         inputnum=jTextArea1.getText()+jButton7.getText();
         number=number+jButton7.getText();
        jTextArea1.setText(inputnum);
       //int ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        try{
           if(jTextArea1.getText().isEmpty()){
               JOptionPane.showMessageDialog(rootPane, "Please Start Your Game","Aleart",JOptionPane.ERROR_MESSAGE); 
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e);            
        }
        switch (operation) {

            case "+":
                
                try {
                    n= Integer.valueOf(number) ;
                   
//                        newGame();
                        //score++;
//                    jTextArea1.setText("Your Ans is Not Right\n\t Game is Over!");
                    //score=0;
                } catch (Exception e) {
//                    jTextArea1.setText("Your Ans is Not Right\n\t Game Over!");
//                    JOptionPane.showMessageDialog(rootPane, "Your Number Format not correct\nPlease Start New Game");
                      JOptionPane.showMessageDialog(rootPane,"Your Number Format not correct\nPlease Start New Game","Alert",JOptionPane.WARNING_MESSAGE); 
                    //JOptionPane.showMessageDialog(rootPane, "Please Start New Game");
                }
//                
//                try{
//                    if(Integer.parseInt(inputnum)!=n1+n2){
//                        
//                    }
//                    //jTextArea1.setText("Your Ans is Not Right\n\t Game is Over!");
//                        
//                        score=0;
//                        //break;
//                }catch(NumberFormatException e){
////                    jTextArea1.setText("Your Ans is Not Right\n\t Game Over!");
//                      JOptionPane.showMessageDialog(null, "Your Number Format not correct");
//                    //break;
//                }

////            
//                if(Integer.parseInt(number)== n1+n2){
//                    jTextArea1.setText("Your Ans is Right");
//                    newGame();
//                    score++;
//                    
//                }
//                else
//                {
//                    jTextArea1.setText("Your Ans is Not Right\n\t Game is Over!");
//                    score=0;
//                    break;
//                }
                
                if(n== sumCheck(n1, n2)){
                    number="";
                 score++;
                 totalGameScore++;
                newGame();
                
                }
                else{
                JOptionPane.showMessageDialog(rootPane,"your score is "+score," Game over",JOptionPane.WARNING_MESSAGE);
                countHighestScore(score);
                countLowestScore(score);
                number="";
                score=0;
                }
                Summary=Summary+"\n "+n1+" + "+n2+" = "+(n1+n2)+" & Your Answer="+n+"; "+(n==(n1+n2));
                break;
                
            case"-":
                try {
//                    if (Integer.parseInt(number) == n5 - n6) {
//
//                        return;
//                    }
                        s= Integer.parseInt(number) ;
                    
                } catch (Exception e) {
//                    jTextArea1.setText("Your Ans is Not Right\n\t Game Over!");
                    JOptionPane.showMessageDialog(rootPane,"Your Number Format not correct\nPlease Start New Game","Alert",JOptionPane.WARNING_MESSAGE); 

                }
                if(s==n5-n6){
                    number="";
                 score++; 
                 totalGameScore++;
                newGame(); 
                
                } 
                else{
                JOptionPane.showMessageDialog(rootPane,"your score is "+score," Game over",JOptionPane.WARNING_MESSAGE);
                countHighestScore(score);
                countLowestScore(score);
                number="";
                score=0;
                }
                                Summary=Summary+"\n "+n5+" - "+n6+" = "+(n5-n6)+" & Your Answer="+s+"; "+(s==(n5-n6));

                break;
                case"X":
                try {
//                    if (Integer.parseInt(number) == n7 * n8) {
//
//                        return;
//                    }
                        t= Integer.parseInt(number) ;
                    
                } catch (Exception e) {
//                    jTextArea1.setText("Your Ans is Not Right\n\t Game Over!");
                    JOptionPane.showMessageDialog(rootPane,"Your Number Format not correct\nPlease Start New Game","Alert",JOptionPane.WARNING_MESSAGE); 

                }
                if(t==n7*n8){
                    number="";
                 score++; 
                 totalGameScore++;
                newGame();
                
                
                } 
                else{
                JOptionPane.showMessageDialog(rootPane,"your score is "+score," Game over",JOptionPane.WARNING_MESSAGE);
                countHighestScore(score);
                countLowestScore(score);
                number="";
                score=0;
                }
                                Summary=Summary+"\n "+n7+" X "+n8+" = "+(n7*n8)+" & Your Answer="+t+"; "+(t==(n7*n8));

                break;
                case"/":
                try {
//                    if (Integer.parseInt(number) == n3 / n4) {
//
//                        return;
//                    }
                        u= Double.parseDouble(number) ;
                    
                } catch (Exception e) {
//                    jTextArea1.setText("Your Ans is Not Right\n\t Game Over!");
                    JOptionPane.showMessageDialog(rootPane,"Your Number Format not correct\nPlease Start New Game","Alert",JOptionPane.INFORMATION_MESSAGE); 

                }
        
            double rAnswer=n3/n4;
            rAnswer=Double.valueOf(new DecimalFormat("##.##").format(rAnswer));
                if(u==rAnswer){
                   number=""; 
                 score++; 
                 totalGameScore++;
                newGame();
                
                } 
                else{
                JOptionPane.showMessageDialog(rootPane,"your score is "+score," Game over",JOptionPane.WARNING_MESSAGE);
                countHighestScore(score);
                countLowestScore(score);
                number="";
                score=0;
                }
                    Summary=Summary+"\n "+(int)n3+" / "+(int)n4+" = "+rAnswer+" & Your Answer="+u+"; "+(u==rAnswer);

                break;

////                
        }
       
        
        
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         inputnum=jTextArea1.getText()+jButton2.getText();
         number=number+jButton2.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        inputnum=jTextArea1.getText()+jButton8.getText();
        number=number+jButton8.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
        // TODO add your handling code here:
        
         inputnum=jTextArea1.getText()+jButtonPoint.getText();
         number=number+jButtonPoint.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         inputnum=jTextArea1.getText()+jButton4.getText();
         number=number+jButton4.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         inputnum=jTextArea1.getText()+jButton6.getText();
         number=number+jButton6.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
         inputnum=jTextArea1.getText()+jButton9.getText();
         number=number+jButton9.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         inputnum=jTextArea1.getText()+jButton5.getText();
         number=number+jButton5.getText();
        jTextArea1.setText(inputnum);
        //number="";
        //ss=Integer.parseInt(jTextArea1.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfileActionPerformed
        // TODO add your handling code here:
        
        if(countGame==0){
            jTextArea1.setText("Your Highest Score is: 0\nYour Lowest Score is: 0\nTotal Played Game: 0\nGame Parsentage: 0.0%");
        }else{
        jTextArea1.setText("Your Highest Score is: "+countHighestScore(score)+"\nYour Lowest Score is: "+countLowestScore+"\nTotal Played Game: "+countGame+"\nGame Parsentage: "+gameParsentage()+"%");
        }
//        Connection conn;
//try {
//            String sql="insert into information (UserName,Pasword,History) values (?,?,?)";
//            conn=DriverManager.getConnection("jdbc:mysql://localhost/registration","root","");
//            PreparedStatement pst = conn.prepareStatement(sql);
//            rs=pst.executeQuery(sql);
//           
////            pst.setString(1,null );
//            pst.setString(1, lg.logInUserName);
//            pst.setString(2,lg.logInPass );
//            pst.setString(3,"Your Highest Score is: "+countHighestScore(score)+"\nYour Lowest Score is: "+countLowestScore+"\nTotal Played Game: "+countGame+"\nGame Parsentage: "+gameParsentage()+"%");
//            pst.executeUpdate();
////          
//            pst.close(); 
//            //JOptionPane.showMessageDialog(rootPane, "Registation succesfull!\n Plese Log in");
//        } catch (Exception e) {
//           JOptionPane.showMessageDialog(rootPane, e);
//        }
    }//GEN-LAST:event_jButtonProfileActionPerformed

    private void jButtonScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScoreActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("Your Score: "+score);
    }//GEN-LAST:event_jButtonScoreActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "Do You Want to Exit?");
        //System.exit(0);
        
//        JOptionPane.showConfirmDialog(rootPane,"Do You Want To Exit?");
        //JOptionPane.ERROR_MESSAGE;
        int a=JOptionPane.showConfirmDialog(rootPane,"Are you sure?","Exit",JOptionPane.YES_NO_OPTION);  
if(a==JOptionPane.YES_OPTION){  
   System.exit(0);  
}  


        
        
        
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        
        String inputnum=jTextArea1.getText()+jButton0.getText();
        number=number+jButton0.getText();
        jTextArea1.setText(inputnum);
        //number="";
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String backSpace;
        if(jTextArea1.getText().length()>0){
            StringBuilder strb = new StringBuilder(jTextArea1.getText());
            strb.deleteCharAt(jTextArea1.getText().length() - 1);
            backSpace =strb.toString();
            jTextArea1.setText(backSpace);
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoryActionPerformed
        // TODO add your handling code here:
       //jTextArea1.setText(jTextArea1.getText());
       

       jTextArea1.setText(Summary);
       //jTextArea1.setText(Summary);
      // jTextArea1.setText(number);
//        int ss=Integer.parseInt(jTextArea1.getText());
//        jTextArea1.setText(String.valueOf(ss));
//        jTextArea1.setText(String.valueOf(s));
//int ss=0;
//        try{
//            ss=Integer.parseInt(jTextArea1.getText());
//        }catch(NumberFormatException e){
//            jTextArea1.setText(String.valueOf(ss));
//        jTextArea1.setText(String.valueOf(s));
//        }
    }//GEN-LAST:event_jButtonHistoryActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        String inputnum=jTextArea1.getText()+jButtonMinus.getText();
        number=jButtonMinus.getText();
        jTextArea1.setText(inputnum);
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"1.You press 'New Game' Button\n2.Then You answer the Math\n3.Then You press 'Next' Button\n4.If You Enter Wrong anser Then \nYour Game is Over!","Help",JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        // TODO add your handling code here:
        dispose();
        new LogInGUI().setVisible(true);
    }//GEN-LAST:event_jButtonLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathLearningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathLearningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathLearningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathLearningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathLearningGUI().setVisible(true);
//                LearnMath lm=new LearnMath();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JButton jButtonProfile;
    private javax.swing.JButton jButtonScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
